// <auto-generated />
using System;
using Chess2_redo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chess2_redo.Migrations
{
    [DbContext(typeof(BoardDbContext))]
    [Migration("20210505223109_adding")]
    partial class adding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chess2_redo.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BoardId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Chess2_redo.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardIdId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("BoardIdId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Chess2_redo.Piece", b =>
                {
                    b.Property<string>("name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("x")
                        .HasColumnType("int");

                    b.Property<int>("y")
                        .HasColumnType("int");

                    b.HasKey("name");

                    b.HasIndex("BoardId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("Chess2_redo.Game", b =>
                {
                    b.HasOne("Chess2_redo.Board", "board")
                        .WithMany()
                        .HasForeignKey("BoardIdId");

                    b.Navigation("board");
                });

            modelBuilder.Entity("Chess2_redo.Piece", b =>
                {
                    b.HasOne("Chess2_redo.Board", null)
                        .WithMany("boardList")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("Chess2_redo.Board", b =>
                {
                    b.Navigation("boardList");
                });
#pragma warning restore 612, 618
        }
    }
}
